minWorkers: 1
maxWorkers: 1
handler:
  model_name: distilbert-base-uncased-finetuned-sst-2-english
  mode: sequence_classification
  do_lower_case: true
  num_labels: 2
  save_mode: pretrained
  max_length: 150
  captum_explanation: true
  embedding_name: distlibert
  BetterTransformer: false
  model_parallel: false
pt2:
  compile:
    enable: false
    backend: inductor
    mode: reduce-overhead
